{
 "title": "Geth Dashboard",
 "description": "Dashboard for Geth node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   { "name": "percentile", "label": "Percentile", "query": "50, 75, 95, 99, 999, 9999" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "system",
     "expr": "system_cpu_sysload",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "system",
     "measurement": "geth.system/cpu/sysload.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "iowait",
     "expr": "system_cpu_syswait",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "iowait",
     "measurement": "geth.system/cpu/syswait.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "geth",
     "expr": "system_cpu_procload",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "geth",
     "measurement": "geth.system/cpu/procload.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "alloc",
     "expr": "system_cpu_sysload",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "system",
     "measurement": "geth.system/memory/allocs.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "used",
     "expr": "system_cpu_syswait",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "iowait",
     "measurement": "geth.system/memory/used.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "held",
     "expr": "system_cpu_procload",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "geth",
     "measurement": "geth.system/memory/held.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "read",
     "expr": "rate(system_disk_readbytes[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "read",
     "measurement": "geth.system/disk/readdata.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "write",
     "expr": "rate(system_disk_writebytes[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "write",
     "measurement": "geth.system/disk/writedata.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "ingress",
     "expr": "rate(p2p_ingress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ingress",
     "measurement": "geth.p2p/ingress.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "egress",
     "expr": "rate(p2p_egress[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "egress",
     "measurement": "geth.p2p/egress.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "peers",
     "expr": "p2p_peers",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "peers",
     "measurement": "geth.p2p/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "dials",
     "expr": "rate(p2p_dials[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "dials",
     "measurement": "geth.p2p/dials.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serves",
     "expr": "rate(p2p_serves[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "serves",
     "measurement": "geth.p2p/serves.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header",
     "measurement": "geth.chain/head/header.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "header",
     "expr": "chain_head_header",
     "legendFormat": "header",
     "measurement": "geth.chain/head/header.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receipt",
     "expr": "chain_head_receipt",
     "legendFormat": "receipt",
     "measurement": "geth.chain/head/receipt.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "block",
     "expr": "chain_head_block",
     "legendFormat": "block",
     "measurement": "geth.chain/head/block.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction slots used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local",
     "measurement": "geth.txpool/slots.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "slots",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.txpool/slots.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.txpool/pending.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped",
     "expr": "txpool_queued",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped",
     "measurement": "geth.txpool/queued.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "local",
     "expr": "txpool_local",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "local",
     "measurement": "geth.txpool/local.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt",
     "measurement": "geth.chain/head/receipt.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Gapped",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued",
     "measurement": "geth.txpool/queued.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Locals",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local",
     "measurement": "geth.txpool/local.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block",
     "measurement": "geth.chain/head/block.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.txpool/pending.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "execution (p=$percentile)",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/execution.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "validation (p=$percentile)",
     "expr": "chain_validation{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "validation (q=$quantile)",
     "measurement": "geth.chain/validation.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "commit (p=$percentile)",
     "expr": "chain_write{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "commit (q=$quantile)",
     "measurement": "geth.chain/write.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account read (p=$percentile)",
     "expr": "chain_account_reads{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account read (q=$quantile)",
     "measurement": "geth.chain/account/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account update (p=$percentile)",
     "expr": "chain_account_updates{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account update (q=$quantile)",
     "measurement": "geth.chain/account/updates.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account hash (p=$percentile)",
     "expr": "chain_account_hashes{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account hashe (q=$quantile)",
     "measurement": "geth.chain/account/hashes.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "account commit (p=$percentile)",
     "expr": "chain_account_commits{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "account commit (q=$quantile)",
     "measurement": "geth.chain/account/commits.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage read (p=$percentile)",
     "expr": "chain_storage_reads{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage read (q=$quantile)",
     "measurement": "geth.chain/storage/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage update (p=$percentile)",
     "expr": "chain_storage_updates{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage update (q=$quantile)",
     "measurement": "geth.chain/storage/updates.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage hash (p=$percentile)",
     "expr": "chain_storage_hashes{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage hashe (q=$quantile)",
     "measurement": "geth.chain/storage/hashes.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "storage commit (p=$percentile)",
     "expr": "chain_storage_commits{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "storage commit (q=$quantile)",
     "measurement": "geth.chain/storage/commits.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "snapshot account read (p=$percentile)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/snapshot/account/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "snapshot storage read (p=$percentile)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/snapshot/storage/reads.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "snapshot commit (p=$percentile)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geth.chain/snapshot/commits.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction processing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "known",
     "expr": "rate(txpool_valid[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "valid",
     "measurement": "geth.txpool/known.meter",
     "query": "SELECT \"m1\" FROM \"geth.txpool/valid.meter\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "valid",
     "expr": "rate(txpool_invalid[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "invalid",
     "measurement": "geth.txpool/valid.meter",
     "query": "SELECT \"m1\" FROM \"geth.txpool/valid.meter\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "invalid",
     "expr": "rate(txpool_underpriced[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "underpriced",
     "measurement": "geth.txpool/invalid.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced",
     "expr": "rate(txpool_pending_discard[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable discard",
     "measurement": "geth.txpool/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable discard",
     "expr": "rate(txpool_pending_replace[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable replace",
     "measurement": "geth.txpool/pending/discard.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable replace",
     "expr": "rate(txpool_pending_ratelimit[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable ratelimit",
     "measurement": "geth.txpool/pending/replace.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable ratelimit",
     "expr": "rate(txpool_pending_nofunds[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "executable nofunds",
     "measurement": "geth.txpool/pending/ratelimit.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "executable nofunds",
     "expr": "rate(txpool_queued_discard[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped discard",
     "measurement": "geth.txpool/pending/nofunds.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped discard",
     "expr": "rate(txpool_queued_replace[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped replace",
     "measurement": "geth.txpool/queued/discard.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped replace",
     "expr": "rate(txpool_queued_ratelimit[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped ratelimit",
     "measurement": "geth.txpool/queued/replace.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped ratelimit",
     "expr": "rate(txpool_queued_nofunds[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "gapped nofunds",
     "measurement": "geth.txpool/queued/ratelimit.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "gapped nofunds",
     "expr": "rate(txpool_valid[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "valid",
     "measurement": "geth.txpool/queued/nofunds.meter",
     "query": "SELECT \"m1\" FROM \"geth.txpool/valid.meter\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block propagation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ingress announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/announces/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/announces/drop.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "malicious announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/announces/dos.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ingress broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/broadcasts/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/broadcasts/drop.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "malicious broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/broadcasts/dos.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ingress announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/known.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "malicious announcements",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/announces/dos.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ingress broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/known.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "otherreject broadcasts",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/broadcasts/otherreject.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "egress requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/out.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "finished requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/done.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "failed requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/fail.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "timed out requests",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/request/timeout.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ingress replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/in.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "known replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/known.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "underpriced replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/underpriced.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "otherreject replies",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/replies/otherreject.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block forwarding",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "receive to announce",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/announces/out.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receive to broadcast",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/block/broadcasts/out.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction fetcher peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "waiting",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/waiting/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "queueing",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/queueing/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetching",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/fetching/peers.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction fetcher hashes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "waiting",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/waiting/hashes.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "queueing",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/queueing/hashes.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "fetching",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.eth/fetcher/transaction/fetching/hashes.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Reorg meters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "reorg add meter",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/add.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "reorg drop meter",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/drop.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Reorg total meters",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "total reorgs",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/executes.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "invalidated transactions",
     "expr": "chain_execution{quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)",
     "measurement": "geth.chain/reorg/invalidTx.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "goroutine count",
     "expr": "txpool_pending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "executable",
     "measurement": "geth.system/cpu/goroutines.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "leveldb read",
     "expr": "eth_db_chaindata_disk_read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/disk/read.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "leveldb write",
     "expr": "eth_db_chaindata_disk_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb write",
     "measurement": "geth.eth/db/chaindata/disk/write.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient read",
     "expr": "eth_db_chaindata_ancient_read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient read",
     "measurement": "geth.eth/db/chaindata/ancient/read.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient write",
     "expr": "eth_db_chaindata_ancient_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/ancient/write.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction read",
     "expr": "eth_db_chaindata_ancient_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/input.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction write",
     "expr": "eth_db_chaindata_ancient_write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/output.meter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Persistent size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "leveldb",
     "expr": "eth_db_chaindata_disk_size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb",
     "measurement": "geth.eth/db/chaindata/disk/size.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient",
     "expr": "eth_db_chaindata_ancient_size",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient",
     "measurement": "geth.eth/db/chaindata/ancient/size.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "leveldb read",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/disk/read.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "leveldb write",
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb write",
     "measurement": "geth.eth/db/chaindata/disk/write.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient read",
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient read",
     "measurement": "geth.eth/db/chaindata/ancient/read.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "ancient write",
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/ancient/write.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction read",
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/input.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "compaction write",
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "ancient write",
     "measurement": "geth.eth/db/chaindata/compact/output.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compaction time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "compaction time",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/compact/time.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Compaction delay",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "write delay",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/compact/writedelay/counter.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Compaction Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Memory compaction",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/compact/memory.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Level0 compaction",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/compact/level0.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Non Level0 compaction",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/compact/nonlevel0.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Seek compaction",
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "legendFormat": "leveldb read",
     "measurement": "geth.eth/db/chaindata/compact/seek.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Light server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client connection number",
   "type": "graph",
   "description": "The number of light client connection\n",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "connection number",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/connection/client.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Client connection duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "duration(p$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/connection/duration.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "System capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total capacity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/totalCapacity.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Connected capacity",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/totalConnected.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total recharge",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total recharge",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/totalRecharge.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Global factor",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/globalFactor.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cost tracker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Recent served time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/recentRequestServed.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Recent estimated time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/recentRequestEstimated.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Serving queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "serving time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/servingQueue/served.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "queued time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/servingQueue/queued.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Client events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "kicked rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/clientEvent/kicked.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "freezed rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/clientEvent/freeze.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rejected rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/clientEvent/rejected.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "connected rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/clientEvent/connected.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "error rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/clientEvent/error.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "disconnected rate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/clientEvent/disconnected.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "In packet total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/total.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request in packet",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 97 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "header packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/header.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "body packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/body.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "code packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/code.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receipt packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/receipt.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "trie proof packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/proof.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "helper trie packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/helperTrie.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txs packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/txs.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tx status packet ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/txStatus.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request out packet",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 97 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "header packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/header.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "body packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/body.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "code packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/code.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receipt packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/receipt.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "trie proof packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/proof.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "helper trie packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/helperTrie.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txs packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/txs.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tx status packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/packets/txStatus.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Out packet total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "packet egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/packets/total.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "In traffic total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/total.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request in traffic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 6, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "header traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/header.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "body traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/body.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "code traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/code.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receipt traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/receipt.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "trie proof traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/proof.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "helper trie traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/helperTrie.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txs traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/txs.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tx status traffic ingress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/in/traffic/txStatus.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request out traffic",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "header traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/header.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "body traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/body.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "code traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/code.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "receipt traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/receipt.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "trie proof traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/proof.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "helper trie traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/helperTrie.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "txs traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/txs.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "tx status traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/txStatus.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Out traffic total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "traffic egress",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/out/traffic/total.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Individual request serving time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "serve header(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/header.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve body(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/body.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve code(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/code.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve receipt(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/receipt.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve trie proof(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/proof.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve helper trie(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/helperTrie.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve txs(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/txs.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "serve tx status(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/misc/serve/txStatus.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Average serving time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/req/avgServedTime.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Average estimated time",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/req/avgEstimatedTime.meter",
     "select": [
      [
       { "params": [ "m1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request time distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Served time(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/req/servedTime.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Estimated time(p=$percentile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/req/estimatedTime.timer",
     "select": [
      [
       { "params": [ "p$percentile" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Served time(mean)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/req/servedTime.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Estimated time(mean)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "geth.les/server/req/estimatedTime.timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}